services:
  development:
    container_name: fcp-fdm-performance-test-suite-development
    build: .
    depends_on:
      floci-init:
        condition: service_completed_successfully
    volumes:
      - ./reports:/opt/perftest/reports
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_SECRET_KEY: test
      AWS_REGION: eu-west-2
      S3_ENDPOINT: 'http://floci:4566'
      RESULTS_OUTPUT_S3_PATH: 's3://fcp-fdm-performance-test-suite'
      ENVIRONMENT: local
      DOMAIN: host.docker.internal
      EVENT_DOMAIN: host.docker.internal
      LOCAL_PORT: 3000
      LOCAL_EVENT_PORT: 3002
      PROTOCOL: http
      DISABLE_EVENTS: ${DISABLE_EVENTS:-false}
      AUTH_ENABLED: ${AUTH_ENABLED:-false}
      TENANT_ID: ${TENANT_ID}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      SCOPE: ${CLIENT_ID}/.default

  floci:
    image: hectorvent/floci:latest
    user: root # Required for S3
    environment:
      FLOCI_HOSTNAME: floci
      FLOCI_DEFAULT_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test

  floci-init:
    image: amazon/aws-cli
    entrypoint: /bin/sh
    command: /setup/init.sh
    depends_on:
      floci:
        condition: service_started
    environment:
      AWS_ENDPOINT_URL: http://floci:4566
      AWS_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    volumes:
      - ./floci/init.sh:/setup/init.sh
